// @ts-nocheck
import {
  SuggestionKeyboard,
  SuggestionKeyboardItem,
} from './SuggestionKeyboard';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SuggestionKeyboard,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7/2.-Components-Library?node-id=6495-22228',
  {
    imports: [
      "import { SuggestionKeyboard, SuggestionKeyboardItem } from '@ledgerhq/ldls-ui-react'",
    ],
    props: {
      // No props available in Figma component
    },
    links: [
      {
        name: 'Documentation',
        url: 'https://ldls.vercel.app/?path=/docs/action-suggestionkeyboard--docs',
      },
      {
        name: 'Storybook',
        url: 'https://ldls.vercel.app/?path=/story/action-suggestionkeyboard--base',
      },
    ],
    example: (props) => (
      <SuggestionKeyboard>
        <SuggestionKeyboardItem>25%</SuggestionKeyboardItem>
        <SuggestionKeyboardItem>50%</SuggestionKeyboardItem>
        <SuggestionKeyboardItem>75%</SuggestionKeyboardItem>
        <SuggestionKeyboardItem>Max</SuggestionKeyboardItem>
      </SuggestionKeyboard>
    ),
  },
);

// SuggestionKeyboardItem - Individual suggestion button
figma.connect(
  SuggestionKeyboardItem,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7/2.-Components-Library?node-id=6495-22238&m=dev',
  {
    imports: [
      "import { SuggestionKeyboardItem } from '@ledgerhq/ldls-ui-react'",
    ],
    props: {
      // Button content
      children: figma.string('label'),
      // Click handler
      onClick: handleSuggestionClick,
    },
    links: [
      {
        name: 'SuggestionKeyboardItem Documentation',
        url: 'https://ldls.vercel.app/?path=/docs/action-suggestionkeyboard--docs#suggestionkeyboarditem',
      },
    ],
    example: (props) => (
      <SuggestionKeyboardItem onClick={props.onClick}>
        {props.children}
      </SuggestionKeyboardItem>
    ),
  },
);
