# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
          - major
      dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
          - major
