// @ts-nocheck
/* eslint-disable */
import { Button } from './Button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=9%3A28',
  {
    imports: [
      "import { Button } from '@ledgerhq/ldls-ui-react'",
      "// import { YourIconName } from '@ledgerhq/ldls-ui-react/Symbols'",
    ],
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum('state', {
        disabled: true,
      }),
      loading: figma.enum('state', {
        loading: true,
      }),
      content: figma.enum('content', {
        text: 'text',
        icon: 'icon',
        iconText: 'iconText',
      }),
      appearance: figma.enum('appearance', {
        base: 'base',
        gray: 'gray',
        accent: 'accent',
        transparent: 'transparent',
        'no-background': 'no-background',
        red: 'red',
      }),
      size: figma.enum('size', {
        xs: 'xs',
        sm: 'sm',
        md: 'md',
        lg: 'lg',
      }),
      label: figma.string('label'),
      icon: figma.instance('icon'),
      // No matching props could be found for these Figma properties:
      // "content": figma.enum('content', {
      //   "text": "text",
      //   "icon-text": "icon-text",
      //   "icon": "icon"
      // })
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/action-button-overview--docs',
      },
    ],
    example: (props) =>
      props.content === 'icon' ? (
        <Button
          disabled={props.disabled}
          loading={props.loading}
          appearance={props.appearance}
          size={props.size}
          icon={props.icon}
        />
      ) : (
        <Button
          disabled={props.disabled}
          loading={props.loading}
          appearance={props.appearance}
          size={props.size}
          icon={props.icon}
        >
          {props.label}
        </Button>
      ),
  },
);
