// @ts-nocheck
import { Dialog, DialogContent, DialogTrigger } from './Dialog';
import { SheetBar } from '../SheetBar/SheetBar';
import { Button } from '../Button/Button';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Dialog,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7/2.-Components-Library?node-id=6345-2641',
  {
    imports: [
      "import { Dialog, DialogContent, DialogTrigger } from '@ledgerhq/ldls-ui-react'",
      "import { SheetBar } from '@ledgerhq/ldls-ui-react'",
      "import { Button } from '@ledgerhq/ldls-ui-react'",
    ],
    props: {
      // Access nested SheetBar properties using figma.nestedProps()
      sheetBar: figma.nestedProps('.sheet-bar', {
        size: figma.enum('size', {
          sm: 'sm',
          lg: 'lg',
        }),
        title: figma.boolean('show-title', {
          true: figma.string('title'),
          false: undefined,
        }),
        description: figma.boolean('show-description', {
          true: figma.string('description'),
          false: undefined,
        }),
        onBack: figma.boolean('show-back-icon', {
          true: onBack,
          false: undefined,
        }),
      }),

      // Dialog close handler
      onClose: onClose,
      setOpen: setOpen,
      open: open,
    },
    links: [
      {
        name: 'Documentation',
        url: 'https://ldls.vercel.app/?path=/docs/components-dialog--docs',
      },
      {
        name: 'Storybook',
        url: 'https://ldls.vercel.app/?path=/story/components-dialog--base',
      },
    ],
    example: (props) => (
      <Dialog open={props.open} onOpenChange={props.setOpen}>
        <DialogTrigger asChild>
          <Button>Open Dialog</Button>
        </DialogTrigger>
        <DialogContent>
          <SheetBar
            size={props.sheetBar.size}
            title={props.sheetBar.title}
            description={props.sheetBar.description}
            onBack={props.sheetBar.onBack}
            onClose={props.onClose}
          />
          <div className="p-16">
            <p>Dialog content goes here</p>
            {/* Content varies based on: {props.contentState} */}
          </div>
        </DialogContent>
      </Dialog>
    ),
  },
);
