// @ts-nocheck
/* eslint-disable */
import { Checkbox } from './Checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=6688%3A3600',
  {
    imports: ["import { Checkbox } from '@ledgerhq/ldls-ui-react'"],
    props: {
      checked: props.checked,
      disabled: props.disabled,
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-checkbox-overview--docs',
      },
    ],
    example: (props) => (
      <Checkbox checked={props.checked} disabled={props.disabled} />
    ),
  },
);
