name: Bug Report
description: Report a bug to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: checkboxes
    id: affected-packages
    attributes:
      label: Which package(s) are affected?
      options:
        - label: "@ledgerhq/lumen-design-core (design tokens)"
        - label: "@ledgerhq/lumen-ui-react (React UI kit)"
        - label: "@ledgerhq/lumen-ui-rnative (React Native UI kit)"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version(s)
      placeholder: "e.g., @ledgerhq/lumen-ui-react@1.2.3"
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component(s) affected
      placeholder: "e.g., Button, Input, Card, or N/A"
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "React version, platform (iOS/Android/Web), browser, OS, etc."
      placeholder: |
        - React/React Native version: 
        - Platform: 
        - Browser/Device: 
        - OS:
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Code snippets, screenshots, error messages, or any other relevant information
      placeholder: You can paste code or drag and drop images here
    validations:
      required: false

