// @ts-nocheck
/* eslint-disable */
import { Switch } from './Switch';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=802%3A186',
  {
    imports: ["import { Switch } from '@ledgerhq/ldls-ui-react'"],
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-switch-overview--docs',
      },
    ],
    props: {
      // These props were automatically mapped based on your linked code:
      selected: figma.boolean('selected', {
        true: true,
        false: false,
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
      size: figma.enum('size', {
        sm: 'sm',
        md: 'md',
      }),
    },
    example: (props) => (
      <Switch
        selected={props.selected}
        disabled={props.disabled}
        size={props.size}
      />
    ),
  },
);
