// @ts-nocheck
/* eslint-disable */
import { Search } from './Search';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Search,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=2248%3A3468',
  {
    imports: ["import { Search } from '@ledgerhq/ldls-ui-react'"],
    props: {
      placeholder: figma.string('label'),
      value: figma.enum('search-state', {
        placeholder: '',
        typing: 'Search text',
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-search-overview--docs',
      },
    ],
    example: (props) => (
      <Search
        placeholder={props.placeholder}
        value={props.value}
        disabled={props.disabled}
      />
    ),
  },
);
