// @ts-nocheck
/* eslint-disable */
import { Tooltip } from './Tooltip';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=6387%3A409',
  {
    imports: [
      "import { Tooltip, TooltipContent, TooltipTrigger } from '@ledgerhq/ldls-ui-react'",
    ],
    props: {
      label: figma.string('label'),
      direction: figma.enum('direction', {
        top: 'top',
        bottom: 'bottom',
        left: 'left',
        right: 'right',
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-tooltip-overview--docs',
      },
    ],
    example: (props) => (
      <Tooltip>
        <TooltipTrigger>
          <button>Hover me</button>
        </TooltipTrigger>
        <TooltipContent side={props.direction}>{props.label}</TooltipContent>
      </Tooltip>
    ),
  },
);
