// @ts-expect-error - figma is not required
import figma from '@figma/code-connect';
import { Switch } from './Switch';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=6688%3A3600',
  {
    imports: ["import { Switch } from '@ledgerhq/ldls-ui-rnative'"],
    props: {
      checked: figma.boolean('checked'),
      disabled: figma.boolean('disabled'),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/react-native_selection-switch--docs',
      },
    ],
    example: (props: { checked: boolean; disabled: boolean }) => (
      <Switch checked={props.checked} disabled={props.disabled} />
    ),
  },
);
