// @ts-nocheck
/* eslint-disable */
import { VerticalListItem } from './VerticalListItem';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  VerticalListItem,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=5783-1328',
  {
    imports: ["import { VerticalListItem } from '@ledgerhq/ldls-ui-react'"],
    props: {
      title: figma.string('title'),
      subtitle: figma.boolean('show-subtitle', {
        true: figma.string('subtitle'),
        false: undefined,
      }),
      spot: <Spot appearance="icon" icon={Settings} />,
      tag: figma.boolean('show-tag', {
        true: figma.instance('tag'),
        false: undefined,
      }),
      secondaryAction: (
        <IconButton
          iconType="stroked"
          aria-label="More actions"
          onClick={() => console.log('secondary action clicked')}
        >
          <MoreVertical />
        </IconButton>
      ),
      disabled: figma.enum('state', {
        disabled: true,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-verticallistitem-overview--docs',
      },
    ],
    example: (props) => (
      <VerticalListItem
        title={props.title}
        subtitle={props.subtitle}
        spot={props.spot}
        tag={props.tag}
        secondaryAction={props.secondaryAction}
        disabled={props.disabled}
      />
    ),
  },
);
