import figma from '@figma/code-connect';
import { Settings } from '../../Symbols';
import { Spot } from '../Spot';
import { Tile } from './Tile';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tile,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=5783-1328',
  {
    imports: ["import { Tile } from '@ledgerhq/lumen-ui-react'"],
    props: {
      title: figma.string('title'),
      description: figma.boolean('show-description', {
        true: figma.string('description'),
        false: undefined,
      }),
      leadingContent: <Spot appearance='icon' icon={Settings} />,
      trailingContent: figma.boolean('show-tag', {
        true: figma.instance('tag'),
        false: undefined,
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-Tile-overview--docs',
      },
    ],
    example: (props) => (
      <Tile
        title={props.title}
        description={props.description}
        leadingContent={props.leadingContent}
        trailingContent={props.trailingContent}
        disabled={props.disabled}
        onPress={() => {
          console.log('Tile pressed');
        }}
      />
    ),
  },
);
