import figma from '@figma/code-connect';
import { Checkbox } from './Checkbox';
import { CheckboxProps } from './types';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=6688%3A3600',
  {
    imports: ["import { Checkbox } from '@ledgerhq/ldls-ui-rnative'"],
    props: {
      checkbox: figma.nestedProps('.checkbox', {
        checked: figma.boolean('checked'),
        disabled: figma.enum('state', {
          disabled: true,
        }),
      }),
      label: figma.boolean('show-label', {
        true: figma.string('label'),
        false: undefined,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/react-native_selection-checkbox--docs',
      },
    ],
    example: (
      props: CheckboxProps & {
        checkbox: { checked: boolean; disabled: boolean };
        label?: string;
      },
    ) => (
      <Checkbox
        checked={props.checkbox.checked}
        disabled={props.checkbox.disabled}
        label={props.label}
      />
    ),
  },
);
