// @ts-nocheck
/* eslint-disable */
import { TileItem } from './TileItem';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TileItem,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=5783-1328',
  {
    imports: ["import { TileItem } from '@ledgerhq/ldls-ui-react'"],
    props: {
      title: figma.string('title'),
      description: figma.boolean('show-description', {
        true: figma.string('description'),
        false: undefined,
      }),
      leadingContent: <Spot appearance='icon' icon={Settings} />,
      trailingContent: figma.boolean('show-tag', {
        true: figma.instance('tag'),
        false: undefined,
      }),
      secondaryAction: (
        <InteractiveIcon
          iconType='stroked'
          aria-label='More actions'
          onClick={() => console.log('secondary action clicked')}
        >
          <MoreVertical />
        </InteractiveIcon>
      ),
      disabled: figma.enum('state', {
        disabled: true,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-TileItem-overview--docs',
      },
    ],
    example: (props) => (
      <TileItem
        title={props.title}
        description={props.description}
        spot={props.spot}
        tag={props.tag}
        secondaryAction={props.secondaryAction}
        disabled={props.disabled}
      />
    ),
  },
);
