// @ts-nocheck
/* eslint-disable */
import { ListItem } from './ListItem';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ListItem,
  'https://www.figma.com/design/JxaLVMTWirCpU0rsbZ30k7?node-id=2255%3A4155',
  {
    imports: ["import { ListItem } from '@ledgerhq/ldls-ui-react'"],
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string('title'),
      description: figma.boolean('show-description', {
        true: figma.string('description'),
        false: undefined,
      }),
      leadingContent: figma.boolean('show-leading-icon', {
        true: figma.instance('leading-icon'),
        false: undefined,
      }),
      descriptionTag: figma.boolean('show-description-tag', {
        true: figma.instance('description'),
        false: undefined,
      }),
      trailingContent: figma.enum('trailing-content', {
        none: undefined,
        chevron: '{<ChevronRight size={24} />}',
        value: figma.boolean('show-subvalue', {
          true: (
            <div className="text-right">
              <div className="body-2-semi-bold">42.00</div>
              <div className="text-muted body-3">USD</div>
            </div>
          ),
          false: <div className="body-2-semi-bold">42.00</div>,
        }),
        icon: figma.instance('trailing-icon'),
        tag: '{<Tag label="New" appearance="accent" />}',
        toggle: '{<Switch selected={selected} />}',
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
    },
    links: [
      {
        name: '*',
        url: 'https://ldls.vercel.app/?path=/docs/components-listitem-overview--docs',
      },
    ],
    example: (props) => (
      <ListItem
        title={props.title}
        description={props.description}
        leadingContent={props.leadingContent}
        descriptionTag={props.descriptionTag}
        trailingContent={props.trailingContent}
        disabled={props.disabled}
      />
    ),
  },
);
