name: Export Figma Design Tokens
on:
  workflow_dispatch:

jobs:
  export-design-tokens:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Export Design Tokens from Figma
        run: npx nx run @ldls/design-tokens:figma-export
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Design tokens
          title: Update Design Tokens
          body: 'Automatically update design tokens through Figma API Local Variables endpoint'
          branch: figma-export-design-tokens
